SWP\Bundle\CoreBundle\Model\Package:
    type: mappedSuperclass
    table: swp_package
    manyToOne:
        organization:
            targetEntity: SWP\Component\MultiTenancy\Model\OrganizationInterface
            joinColumn:
                name: organization_id
                referencedColumnName: id
                nullable: false
    manyToMany:
        articles:
            targetEntity: SWP\Bundle\ContentBundle\Model\ArticleInterface
            joinTable:
                name: swp_package_articles
                joinColumns:
                    package_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    article_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: "CASCADE"
