SWP\Bundle\CoreBundle\Model\Route:
    type: entity
    table: swp_route
    fields:
        tenantCode:
            type: string
        paywallSecured:
            type: boolean
            nullable: true
    uniqueConstraints:
        swp_route_name_idx:
            columns: [ name, tenant_code ]
    oneToMany:
        events:
            targetEntity: SWP\Bundle\AnalyticsBundle\Model\ArticleEventInterface
            mappedBy: impressionRoute