SWP\Bundle\CoreBundle\Model\Rule:
    type: mappedSuperclass
    table: swp_rule
    fields:
        tenantCode:
            type: string
    manyToOne:
        organization:
            targetEntity: SWP\Component\MultiTenancy\Model\OrganizationInterface
            joinColumn:
                name: organization_id
                referencedColumnName: id
                nullable: false
