SWP\Bundle\CoreBundle\Model\User:
    type:  mappedSuperclass
    table: swp_user
    manyToOne:
        organization:
            targetEntity: SWP\Component\MultiTenancy\Model\OrganizationInterface
            joinColumn:
                name: organization_id
                referencedColumnName: id
                nullable: false
    oneToMany:
        subscriptions:
            targetEntity: SWP\Component\Paywall\Model\SubscriptionInterface
            mappedBy: user
