FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api]
        username:
            expose: true
            groups: [api]
        email:
            expose: true
            groups: [api]
        lastLogin:
            expose: true
            groups: [api]
        roles:
            expose: true
            groups: [api]
