SWP\Bundle\CoreBundle\Model\Package:
    exclusion_policy: ALL
    properties:
        articles:
            expose: true
            groups: [api, api_packages_list]
        status:
            expose: true
            type: string
            groups: [api, api_packages_list]
