SWP\Bundle\CoreBundle\Model\Package:
    exclusion_policy: ALL
    properties:
        articles:
            expose: true
            groups: [api]
        status:
            expose: true
            type: string
            groups: [api]
