SWP\Bundle\CoreBundle\Model\ContentList:
    exclusion_policy: ALL
    properties:
        themeName:
            expose: true
            type: string
        domainName:
            expose: true
            type: string
        organization:
            expose: true
            type: SWP\Bundle\CoreBundle\Model\Organization
        ampEnabled:
          expose: true
    relations:
        -   rel: self
            href:
                route: swp_api_content_show_lists
                parameters:
                    id: expr(object.getId())
        -   rel: items
            href:
                route: swp_api_core_list_items
                parameters:
                    id: expr(object.getId())
