SWP\Bundle\CoreBundle\Model\FacebookApplication:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: [api]
        appId:
            expose: true
            groups: [api]
            type: integer
        appSecret:
            expose: true
            groups: [api]
            type: string
        createdAt:
            expose: true
            groups: [api]
            type: DateTime
        updatedAt:
            expose: true
            groups: [api]
            type: DateTime
    relations:
        -   rel: list
            href:
                route: swp_api_list_facebook_applications
