SWP\Bundle\CoreBundle\Model\FacebookInstantArticlesArticle:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api]
            type: string
        submissionId:
            expose: true
            groups: [api]
            type: string
        article:
            expose: true
            groups: [api]
            type: SWP\Bundle\CoreBundle\Model\Article
        status:
            expose: true
            groups: [api]
            type: string
        errors:
            expose: true
            groups: [api]
            type: string
        feed:
            expose: true
            groups: [api]
            type: SWP\Bundle\CoreBundle\Model\FacebookInstantArticlesFeed
        createdAt:
            expose: true
            groups: [api]
            type: DateTime
        updatedAt:
            expose: true
            groups: [api]
            type: DateTime
    relations:
        -   rel: list
            href:
                route: swp_api_list_facebook_instant_articles_articles
        -   rel: update_status
            href:
                route: swp_api_facebook_instant_articles_articles_update
                parameters:
                    submissionId: expr(object.getSubmissionId())
