SWP\Bundle\CoreBundle\Model\Route:
    exclusion_policy: ALL
    properties:
        articlesCount:
            serialized_name: articlesCount
            expose: true
            groups: [api]
            type: SWP\Bundle\CoreBundle\Model\ArticlesCountInterface
        paywallSecured:
            expose: true
            groups: [api]
            type: boolean
