SWP\Bundle\CoreBundle\Model\Article:
    exclusion_policy: ALL
    properties:
        isPublishedFBIA:
            expose: true
            groups: [api]
        tenantCode:
            serialized_name: tenant
            expose: true
            groups: [api]
        articleStatistics:
            expose: true
            groups: [api]
        externalArticle:
            expose: true
            groups: [api]
        paywallSecured:
            expose: true
            groups: [api]
            type: boolean
        contentLists:
            expose: true
            groups: [api]
        commentsCount:
            expose: true
            groups: [api]
            access_type: public_method
    relations:
        -
            rel: slideshows
            href:
                route: swp_api_slideshows_list
                parameters:
                    articleId: "expr(object.getId())"
            exclusion:
                exclude_if: "expr(object.getId() === null)"
