SWP\Bundle\CoreBundle\Model\Container:
    exclusion_policy: ALL
    properties:
        uuid:
            expose: true
            groups: [api]
            type: string
        revision:
            expose: true
            groups: [api]
    relations:
        -
            rel: self
            href:
                route: swp_api_templates_get_container
                parameters:
                    uuid: expr(object.getUuid())
